### ISSUE TITLE
JSON object: invalid object format,

### ISSUE THREAD

**Issue by nimafire** [malav097/cloudflare-zabbix#2]
Error LOG:

15921:20200413:113634.805 discovery rule "HOST_status_codes:cloudflare.py[-l, HOST]" became not supported: Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/cloudflare.py", line 14, in <module>
    cloudflare_user = conf['CREDENTIALS

**Comment by malav097** [comment]
Hi, please make sure to use the `cloudflare.ini` file, put the information of your Zabbix server and make sure the permissions of the file are set correctly. By reading the `HOST_status_codes:cloudflare.py[-l, HOST]` of your error i can see that HOST is not a valid host to use

**Comment by nimafire** [comment]
ive change correct hostname with HOST when send error here
.ini file is configure correctly with cloudflare api, zabbix url, zabbix username, zabbix password

-rwxr-xr-x 1 zabbix zabbix  941 Apr 13 11:32 cloudflare.ini
-rwxr-xr-x 1 zabbix zabbix 5499 Nov  8 10:58 cloudflare.py

for this parameter in .ini file "hosts_list"
there is an active host in zabbix server, ive enter hostname of that host in hosts_list

**Comment by malav097** [comment]
ok thats where you got it wrong, you have to put a list of the hostnames of cloudflare hosts that you want to monitor on `hosts_list`, you should not create anything on the Zabbix side, the script should create every item for you when you run it with the `--create` parameter

**Comment by malav097** [comment]
This is a example of how it should be:


```
[CREDENTIALS]
cloudflare_user = *****************
cloudflare_token = ******************

zabbix_user = *****
zabbix_password = *****

zabbix_url = http://127.0.0.1/zabbix

[HOSTS]
hosts_list = ado******.com
             co*****uile.com
             *****ave.com
             imov****n.com
             im*****b.com.br
             *******.com
             *******dn.com
```

**Comment by nimafire** [comment]
thats what ive done before,
put list of my servers hostname in hosts_list.
check this:
hosts_list = server.domain.com
i have an active server.domain.com host in zabbix with lots of triger and item.

**Comment by malav097** [comment]
> thats what ive done before,
> put list of my servers hostname in hosts_list.
> check this:
> hosts_list = server.domain.com
> i have an active server.domain.com host in zabbix with lots of triger and item.

but is not the zabbix host that should be there, is the Cloudflare host, your Cloudflare domain

**Comment by nimafire** [comment]
mm ok in this case, hosts_list means list of domains under a cloudflare account that we want to monitor.
i have rerun --create parameter and now new host create with these detailes:

DOMAIN.COM_status_codes | Applications | Items | Triggers | Graphs | Discovery 1 | Web | 127.0.0.1: 10050

**Comment by malav097** [comment]
> mm ok in this case, hosts_list means list of domains under a cloudflare account that we want to monitor.
> i have rerun --create parameter and now new host create with these detailes:
> 
> DOMAIN.COM_status_codes | Applications | Items | Triggers | Graphs | Discovery 1 | Web | 127.0.0.1: 10050


yes, that is what the script should do :) wait till it populates the data of the items

**Comment by malav097** [comment]
i will update the documentation because it seems that the `hosts_list` option is not well explained

**Comment by nimafire** [comment]
i Appreciate that,
is it normal that still havent any data in "latest data" ? no error log and no data as well

**Comment by malav097** [comment]
Yes it is norma, step 5 in the documentation ` 5) Wait for 30 minutes and the items data will be populated.`

**Comment by nimafire** [comment]
mm
still have error:

14517:20200413:172636.402 discovery rule "DOMAIN.COM_status_codes:cloudflare.py[-l, DOMAIN.COM]" became not supported: Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/cloudflare.py", line 14, in <module>

its refer to invalid format

**Comment by malav097** [comment]
you can try the script manually first to see the whole error, try this  `sudo -u zabbix python3 /usr/lib/zabbix/externalscripts/cloudflare.py -l DOMAIN.COM`  dont try it with another user than zabbix

**Comment by nimafire** [comment]
ive use cloudflare global key

[root@zabbix externalscripts]# sudo -u zabbix python3 /usr/lib/zabbix/externalscripts/cloudflare.py -l DOMAIN.COM
Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/cloudflare.py", line 210, in <module>
    main()
  File "/usr/lib/zabbix/externalscripts/cloudflare.py", line 177, in main
    data_t = get_status(zone, cf)
  File "/usr/lib/zabbix/externalscripts/cloudflare.py", line 87, in get_status
    response = api.zones.analytics.dashboard.get(zone_id, params={'since': '-30', 'util': '0'})
  File "/usr/local/lib/python3.6/site-packages/CloudFlare/cloudflare.py", line 618, in get
    params, data)
  File "/usr/local/lib/python3.6/site-packages/CloudFlare/cloudflare.py", line 75, in call_with_auth
    params, data, files)
  File "/usr/local/lib/python3.6/site-packages/CloudFlare/cloudflare.py", line 467, in _call
    raise CloudFlareAPIError(code, message, error_chain)
CloudFlare.exceptions.CloudFlareAPIError: Please check time interval or your plan level

i still have to wait, ha?

**Comment by malav097** [comment]
It seems that your cloudflare plan level does not offer you the status codes API metrics my friend

**Comment by malav097** [comment]
I am going to close this issue because is not directly related to the code of the script.

**Comment by nimafire** [comment]
TNX from your update, please mention on readme about this cloudflare option must be active first,
im on free plan, should i upgrade to 20$ plan for this API option?
is it only actiive on paid plan ?

**Comment by nimafire** [comment]
TNX from your update, please mention on readme " this cloudflare option must be active first "
its paid option,  why you relay on this option to detect error 500 ?

**Comment by malav097** [comment]
This is just some work i have done on my job my company asked me for this so they can se the percentage of status codes 5xx. About Cloudflare, you should read their plans and what they offer. Good luck buddy.

**Comment by nimafire** [comment]
your job and publish what you do is awesome, however i cant work with it at this time but i appreciate that :)
maybe upgrade my plan to test your code in my side :)
